// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jctjldwqkafywqtcrxxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdGpsZHdxa2FmeXdxdGNyeHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODg3NDksImV4cCI6MjA1NzU2NDc0OX0.VP_u1DIAGOizOhSnJkALxR78LEEmv2b11B_DGNEdJWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);